#!/bin/sh

# Used when it is needed to force a major release. For instance,
# when releasing the first version if you do not want it to be 0.x.x

set -e

bump=major
version=$(npm --no-git-tag-version --silent --force version $bump)
message="release: $version"
npx conventional-changelog -p angular-bitbucket -i CHANGELOG.md -s
git add package.json CHANGELOG.md
git commit --quiet -m "$message"
git tag -a $version -m "$message"


