#!/bin/sh

set -e

bump=$(npx conventional-recommended-bump -p angular)
version=$(npm --no-git-tag-version --silent --force version $bump)
message="release: $version"
npx conventional-changelog -p angular-bitbucket -i CHANGELOG.md -s
git add package.json CHANGELOG.md
git commit --quiet -m "$message"
git tag -a $version -m "$message"


