#!/bin/sh

set -e

yarn --silent clean
mkdir build
files="src node_modules .npmignore package.json tsconfig.json yarn.lock LICENSE README.md CHANGELOG.md"

# copy only those files that exists
for f in $files
do
  if [ -e $f ]; then
    cp -rf $f build
  fi
done

cd build

yarn --silent build --outDir .

sed -i -e 's/build\/index/index/g' package.json
